spring:
  application:
    name: OOTDay

  datasource:
    url: jdbc:postgresql://localhost:5432/ootday

  jpa:
    hibernate:
      ddl-auto: none              # 운영 환경에서는 none 권장
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    vertex:
      ai:
        gemini:
          project-id: api-test-466115
          location: us-central1


