name: CD - Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ~/app/4th-MVP-OOTDay-Server
            git pull origin main
            chmod +x ./gradlew
            ./gradlew clean build -x test
            if [ -f app.pid ]; then kill -9 $(cat app.pid) || true; rm -f app.pid; fi
            nohup env GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/vertex/key.json \
                     VERTEX_PROJECT_ID=ootdays \
                     VERTEX_LOCATION=us-central1 \
                     java -jar build/libs/OOTDay-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo $! > app.pid
