name: CD - Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
              set -e
            
              cd ~/app/4th-MVP-OOTDay-Server
            
              echo ">>> Pull latest code"
              git pull origin main
            
              echo ">>> Build"
              ./gradlew clean build -x test
            
              echo ">>> Stop old process (if any)"
              if [ -f app.pid ] && ps -p $(cat app.pid) > /dev/null 2>&1; then
                kill $(cat app.pid) || true
                sleep 2
              fi
              pkill -f 'OOTDay-0.0.1-SNAPSHOT.jar' || true
            
              echo ">>> Start new process"
              # 로그 초기화(선택)
              : > app.log
            
              nohup env GOOGLE_APPLICATION_CREDENTIALS=/home/ubuntu/vertex/key.json \
                   VERTEX_PROJECT_ID=ootdays \
                   VERTEX_LOCATION=us-central1 \
                   java -jar build/libs/OOTDay-0.0.1-SNAPSHOT.jar \
                   >> app.log 2>&1 < /dev/null &
            
              echo $! > app.pid
              sleep 2
            
              echo ">>> Sanity check"
              ps -p $(cat app.pid) -o pid,cmd=
              tail -n 50 app.log
